/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_balinhui_fpa_nativeapis_Global */

#ifndef _Included_org_balinhui_fpa_nativeapis_Global
#define _Included_org_balinhui_fpa_nativeapis_Global
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_balinhui_fpa_nativeapis_Global
 * Method:    chooseFiles
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_balinhui_fpa_nativeapis_Global_chooseFiles
  (JNIEnv *, jclass);

/*
 * Class:     org_balinhui_fpa_nativeapis_Global
 * Method:    message
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_balinhui_fpa_nativeapis_Global_message
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
