/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_balinhui_fpa_Action */

#ifndef _Included_org_balinhui_fpa_Action
#define _Included_org_balinhui_fpa_Action
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_balinhui_fpa_Action
 * Method:    chooseFiles
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_balinhui_fpa_Action_chooseFiles
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
