/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_balinhui_fpa_nativeapis_ITaskBarListAPI */

#ifndef _Included_org_balinhui_fpa_nativeapis_ITaskBarListAPI
#define _Included_org_balinhui_fpa_nativeapis_ITaskBarListAPI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_NOPROGRESS
#define org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_NOPROGRESS 0L
#undef org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_INDETERMINATE
#define org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_INDETERMINATE 1L
#undef org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_NORMAL
#define org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_NORMAL 2L
#undef org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_ERROR
#define org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_ERROR 4L
#undef org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_PAUSED
#define org_balinhui_fpa_nativeapis_ITaskBarListAPI_TBPF_PAUSED 8L
/*
 * Class:     org_balinhui_fpa_nativeapis_ITaskBarListAPI
 * Method:    initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_balinhui_fpa_nativeapis_ITaskBarListAPI_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_balinhui_fpa_nativeapis_ITaskBarListAPI
 * Method:    setProgressState
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_balinhui_fpa_nativeapis_ITaskBarListAPI_setProgressState
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_balinhui_fpa_nativeapis_ITaskBarListAPI
 * Method:    setProgressValue
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_balinhui_fpa_nativeapis_ITaskBarListAPI_setProgressValue
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_balinhui_fpa_nativeapis_ITaskBarListAPI
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_balinhui_fpa_nativeapis_ITaskBarListAPI_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
